// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RetailSite.Products.Api.DAL.Contexts;

namespace RetailSite.Products.Api.Migrations
{
    [DbContext(typeof(ProductsContext))]
    partial class ProductsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RetailSite.Products.Api.DAL.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescriptionLong")
                        .IsRequired()
                        .HasMaxLength(2500);

                    b.Property<string>("DescriptionShort")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new { Id = 1, DescriptionLong = "Fried rice dishes long description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fermentum metus sed tincidunt ullamcorper. Nullam dignissim massa non magna tristique, in condimentum quam ultricies. Pellentesque pretium orci sem, vitae ornare elit tincidunt ut. Pellentesque tortor mi, volutpat nec lectus in, egestas mollis risus. Sed aliquam tristique mollis. Fusce vel sapien nec odio iaculis suscipit non nec justo. Nunc egestas elit a nunc venenatis auctor. Suspendisse tellus neque, viverra eu massa sit amet, fringilla finibus velit. Nam at sapien sapien. Vivamus venenatis lorem urna, eget posuere massa lobortis eget.", DescriptionShort = "Fried rice dishes short description.", Name = "Fried Rice Dishes" },
                        new { Id = 2, DescriptionLong = "Noodle dishes long description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fermentum metus sed tincidunt ullamcorper. Nullam dignissim massa non magna tristique, in condimentum quam ultricies. Pellentesque pretium orci sem, vitae ornare elit tincidunt ut. Pellentesque tortor mi, volutpat nec lectus in, egestas mollis risus. Sed aliquam tristique mollis. Fusce vel sapien nec odio iaculis suscipit non nec justo. Nunc egestas elit a nunc venenatis auctor. Suspendisse tellus neque, viverra eu massa sit amet, fringilla finibus velit. Nam at sapien sapien. Vivamus venenatis lorem urna, eget posuere massa lobortis eget.", DescriptionShort = "Noodle dishes short description.", Name = "Noodle Dishes" },
                        new { Id = 3, DescriptionLong = "Curry dishes long description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fermentum metus sed tincidunt ullamcorper. Nullam dignissim massa non magna tristique, in condimentum quam ultricies. Pellentesque pretium orci sem, vitae ornare elit tincidunt ut. Pellentesque tortor mi, volutpat nec lectus in, egestas mollis risus. Sed aliquam tristique mollis. Fusce vel sapien nec odio iaculis suscipit non nec justo. Nunc egestas elit a nunc venenatis auctor. Suspendisse tellus neque, viverra eu massa sit amet, fringilla finibus velit. Nam at sapien sapien. Vivamus venenatis lorem urna, eget posuere massa lobortis eget.", DescriptionShort = "Curry dishes short description.", Name = "Curry Dishes" },
                        new { Id = 4, DescriptionLong = "Noodle dishes long description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fermentum metus sed tincidunt ullamcorper. Nullam dignissim massa non magna tristique, in condimentum quam ultricies. Pellentesque pretium orci sem, vitae ornare elit tincidunt ut. Pellentesque tortor mi, volutpat nec lectus in, egestas mollis risus. Sed aliquam tristique mollis. Fusce vel sapien nec odio iaculis suscipit non nec justo. Nunc egestas elit a nunc venenatis auctor. Suspendisse tellus neque, viverra eu massa sit amet, fringilla finibus velit. Nam at sapien sapien. Vivamus venenatis lorem urna, eget posuere massa lobortis eget.", DescriptionShort = "Noodle dishes short description.", Name = "\"Lite\" Dishes" }
                    );
                });

            modelBuilder.Entity("RetailSite.Products.Api.DAL.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId");

                    b.Property<string>("DescriptionLong")
                        .IsRequired()
                        .HasMaxLength(2500);

                    b.Property<string>("DescriptionShort")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new { Id = 1, CategoryId = 1, DescriptionLong = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fermentum metus sed tincidunt ullamcorper. Nullam dignissim massa non magna tristique, in condimentum quam ultricies. Pellentesque pretium orci sem, vitae ornare elit tincidunt ut. Pellentesque tortor mi, volutpat nec lectus in, egestas mollis risus. Sed aliquam tristique mollis. Fusce vel sapien nec odio iaculis suscipit non nec justo. Nunc egestas elit a nunc venenatis auctor. Suspendisse tellus neque, viverra eu massa sit amet, fringilla finibus velit. Nam at sapien sapien. Vivamus venenatis lorem urna, eget posuere massa lobortis eget.", DescriptionShort = "Stir-fried Jasmine white rice, scrambled egg, onion, scallion and tomato.", Name = "Koa Pad", Price = 6.95m },
                        new { Id = 2, CategoryId = 2, DescriptionLong = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fermentum metus sed tincidunt ullamcorper. Nullam dignissim massa non magna tristique, in condimentum quam ultricies. Pellentesque pretium orci sem, vitae ornare elit tincidunt ut. Pellentesque tortor mi, volutpat nec lectus in, egestas mollis risus. Sed aliquam tristique mollis. Fusce vel sapien nec odio iaculis suscipit non nec justo. Nunc egestas elit a nunc venenatis auctor. Suspendisse tellus neque, viverra eu massa sit amet, fringilla finibus velit. Nam at sapien sapien. Vivamus venenatis lorem urna, eget posuere massa lobortis eget.", DescriptionShort = "Stir-fried thin rice noodles with chopped shallot, chopped turnip, scrambled egg, scallion, bean sprouts, fried tofu and crushed peanuts.", Name = "Royal Pad Thai", Price = 6.95m },
                        new { Id = 3, CategoryId = 2, DescriptionLong = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fermentum metus sed tincidunt ullamcorper. Nullam dignissim massa non magna tristique, in condimentum quam ultricies. Pellentesque pretium orci sem, vitae ornare elit tincidunt ut. Pellentesque tortor mi, volutpat nec lectus in, egestas mollis risus. Sed aliquam tristique mollis. Fusce vel sapien nec odio iaculis suscipit non nec justo. Nunc egestas elit a nunc venenatis auctor. Suspendisse tellus neque, viverra eu massa sit amet, fringilla finibus velit. Nam at sapien sapien. Vivamus venenatis lorem urna, eget posuere massa lobortis eget.", DescriptionShort = "Stir-fried thin rice noodles with scrambled egg, broccoli, Napa cabbage and carrot in a sweet black soy sauce.", Name = "Pad See Ew", Price = 6.95m },
                        new { Id = 4, CategoryId = 2, DescriptionLong = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fermentum metus sed tincidunt ullamcorper. Nullam dignissim massa non magna tristique, in condimentum quam ultricies. Pellentesque pretium orci sem, vitae ornare elit tincidunt ut. Pellentesque tortor mi, volutpat nec lectus in, egestas mollis risus. Sed aliquam tristique mollis. Fusce vel sapien nec odio iaculis suscipit non nec justo. Nunc egestas elit a nunc venenatis auctor. Suspendisse tellus neque, viverra eu massa sit amet, fringilla finibus velit. Nam at sapien sapien. Vivamus venenatis lorem urna, eget posuere massa lobortis eget.", DescriptionShort = "Stir-fried thin rice noodles with onion, bell pepper, mushroom, carrot and sweet Thai basil in a spicy and sweet chili sauce.", Name = "Pad Kee Maow (Drunken Noodles)", Price = 6.95m },
                        new { Id = 5, CategoryId = 3, DescriptionLong = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fermentum metus sed tincidunt ullamcorper. Nullam dignissim massa non magna tristique, in condimentum quam ultricies. Pellentesque pretium orci sem, vitae ornare elit tincidunt ut. Pellentesque tortor mi, volutpat nec lectus in, egestas mollis risus. Sed aliquam tristique mollis. Fusce vel sapien nec odio iaculis suscipit non nec justo. Nunc egestas elit a nunc venenatis auctor. Suspendisse tellus neque, viverra eu massa sit amet, fringilla finibus velit. Nam at sapien sapien. Vivamus venenatis lorem urna, eget posuere massa lobortis eget.", DescriptionShort = "A mild mussamun curry paste simmered in creamy coconut milk with bell pepper, potato, carrot, broccoli and peanuts.", Name = "Mussamun Curry", Price = 6.95m }
                    );
                });

            modelBuilder.Entity("RetailSite.Products.Api.DAL.Entities.Product", b =>
                {
                    b.HasOne("RetailSite.Products.Api.DAL.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
